authz_admin:
  api_key: ${AUTHZ_ADMIN_API_KEY}
  jwks: ${PUB_JWKS}
  bind_port: 8000
  required_accounts:
    p.van.beek@amsterdam.nl:
      - DPB
    Medewerker:
      - CDE
    signals.admin@amsterdam.nl:
      - SIG_ROLE
  datasets:
    SIG:
      name: Meldingen
      scopes:
        ALL:
          name: Volledig
    BRP:
      name: Basis Register Personen
      scopes:
        R:
          name: Leesrechten
    TLLS:
      name: Tellus
      scopes:
        R:
          name: Leesrechten
    BRK:
      name: Kadaster
      scopes:
        RSN:
          name: Read Subject Natuurlijk
          description: >
            Alle atrributen van een kadastraal subject (natuurlijk en niet-natuurlijk),
            inclusief alle rechten op kadastrale objecten
          includes: RS
        RS:
          name: Read Subject
          description: >
            Alle attributen van een kadastraal niet-natuurlijk subject, inclusief alle
            rechten op kadastrale objecten
          included_by: RSN
        RO:
          name: Read Object
          description: >
            Alle attributen van een kadastraal object, inclusief koopsom, koopsom_valuta_code,
            koopjaar, cultuurcode_onbebouwd, cultuurcode_bebouwd en zakelijke rechten van de
            bijbehorende kadastrale subjecten
    WKPB:
      name: Wet Kenbaarheid Publiekrechtelijke Beperkingen
      described_by: 'https://www.amsterdam.nl/stelselpedia/wkpb-index/'
      scopes:
        RBDU:
          name: Lezen URL Brondocument

#    WOZ:
#      name: Waardebepaling Onroerende Zaken
#      described_by: 'https://www.amsterdam.nl/stelselpedia/woz-index/'
#      scopes: {}
    MON:
      name: Monumenten
      described_by: 'https://www.amsterdam.nl/stelselpedia/monumenten-index/'
      scopes:
        RBC:
          name: Lezen beschrijvingen van Complexen
          description: >-
            Beschrijvingen van complexen bevatten soms (inbraak-)gevoelige
            informatie.
        RDM:
          name: Lezen details van Monumenten
          description: >-
            - architect_ontwerp_monument
            - monumenttype
            - opdrachtgever_bouw_monument
            - bouwjaar_start_bouwperiode_monument
            - bouwjaar_eind_bouwperiode_monument
            - oorspronkelijke_functie_monument
            - monumentgeometrie
            - in_onderzoek
            - beschrijving_monument
            - redengevende_omschrijving_monument
    HR:
      name: Handelsregister
      described_by: 'https://www.amsterdam.nl/stelselpedia/hr-index/'
      scopes:
        R:
          name: Leesrechten
          description: >-
            De informatie in deze dataset is volgens bronhouder niet publiek.
            Deze dataset is niet gelijk aan het “officiële” handelsregister.
    AUR:
      name: Rollen van ADW accounts
      described_by: 'https://dokuwiki.datapunt.amsterdam.nl/'
      scopes:
        R:
          name: Rollen van gebruikers bevragen
          description: >-
            Geeft het recht om de rollen in te zien behorende bij een ADW
            account.
          included_by: W
        W:
          name: Rollen van gebruikers wijzigen
          description: >-
            Geeft het recht om rollen aan een ADW account toe te voegen en
            rollen van een ADW account te verwijderen.
          includes: R
    GREX:
      name: Grondexploitatie
      described_by: 'https://dokuwiki.datapunt.amsterdam.nl/'
      scopes:
        R:
          name: Leesrechten
          description: >-
            De informatie in deze dataset is volgens bronhouder niet publiek.
  profiles:
    AZB:
      name: Autorisatiebeheer
      description: |-
        Het toekennen van rollen aan ADW accounts, om de eigenaars van deze
        accounts toegang te geven tot voor hen relevante data.
      scopes:
        - AUR/R
        - AUR/W
    GA_020:
      name: Gemeenteambtenaar
      description: |-
        Gewone beheertaken.

        To Do
            vervangen door nauwkeuriger profiel
      scopes:
        - HR/R
        - MON/RBC
        - MON/RDM
        - WKPB/RBDU
        - BRK/RS
        - BRK/RO
        - TLLS/R
        - GREX/R
    SA_020:
      name: Superambtenaar
      description: |-
        Handhaving en opsporing

        To Do
            vervangen door nauwkeuriger profiel
      scopes:
        - BRK/RSN
    SIGGUY:
      name: Meldingenguy
      description: You know
      scopes:
        - SIG/ALL
  roles:
    CDE:
      name: medewerker
      description: |-
        Deze rol is tijdelijk.

        To Do
            vervangen door nauwkeuriger rolverdeling
      profiles:
        - GA_020
    CDE_PLUS:
      name: speciaal bevoegd
      description: |-
        Deze rol is tijdelijk.

        To Do
            vervangen door nauwkeuriger rolverdeling
      profiles:
        - SA_020
        - GA_020
    DPB:
      name: beheerder gebruikersrollen
      description: |-
        Deze beheerders voeren onder andere het accountbeheer uit.

        To Do
            vervangen door nauwkeuriger rolverdeling
      profiles:
        - AZB
    SIG_ROLE:
      name: Signal guy
      description: You know
      profiles:
        - SIGGUY


postgres:
  host: ${DB_HOST:-database}
  port: ${DB_PORT:-5432}
  user: ${DB_USER:-authz_admin}
  password: ${DB_PASS:-authz_admin}
  dbname: ${DB_DATABASE:-authz_admin}

logging:
  version: 1
  formatters:
    default:
      format: '%(asctime)s authz_admin %(levelname)-8s %(module)s:%(lineno)d: %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: default
    aiohttp.access:
      class: logging.StreamHandler
  loggers:
    authz_admin:
      level: ${LOGLEVEL:-DEBUG}
      handlers: [console]
      propagate: false
    aiohttp.access:
      level: ${LOGLEVEL:-DEBUG}
      handlers: [aiohttp.access]
      propagate: false
    aiohttp:
      propagate: true
#    aiohttp.*:
#      propagate: true
    rest_utils:
      level: ${LOGLEVEL:-DEBUG}
      handlers: [console]
      propagate: false
    config_loader:
      level: ${LOGLEVEL:-DEBUG}
      handlers: [console]
      propagate: false
  root:
    level: ${LOGLEVEL:-WARNING}
    handlers: [console]
